//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.04 at 06:05:49 PM EET 
//


package com.messagesaver.messages;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.messagesaver.messages package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.messagesaver.messages
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Message }
     * 
     */
    public Message createMessage() {
        return new Message();
    }

    /**
     * Create an instance of {@link GetAllMessagesRequest }
     * 
     */
    public GetAllMessagesRequest createGetAllMessagesRequest() {
        return new GetAllMessagesRequest();
    }

    /**
     * Create an instance of {@link GetAllMessagesResponse }
     * 
     */
    public GetAllMessagesResponse createGetAllMessagesResponse() {
        return new GetAllMessagesResponse();
    }

    /**
     * Create an instance of {@link GetAllAuthorMessagesRequest }
     * 
     */
    public GetAllAuthorMessagesRequest createGetAllAuthorMessagesRequest() {
        return new GetAllAuthorMessagesRequest();
    }

    /**
     * Create an instance of {@link GetAllAuthorMessagesResponse }
     * 
     */
    public GetAllAuthorMessagesResponse createGetAllAuthorMessagesResponse() {
        return new GetAllAuthorMessagesResponse();
    }

    /**
     * Create an instance of {@link AddMessageRequest }
     * 
     */
    public AddMessageRequest createAddMessageRequest() {
        return new AddMessageRequest();
    }

    /**
     * Create an instance of {@link AddMessageResponse }
     * 
     */
    public AddMessageResponse createAddMessageResponse() {
        return new AddMessageResponse();
    }

    /**
     * Create an instance of {@link DeleteMessagesByAuthorRequest }
     * 
     */
    public DeleteMessagesByAuthorRequest createDeleteMessagesByAuthorRequest() {
        return new DeleteMessagesByAuthorRequest();
    }

}
